[tool.poetry]
name = "fplayer"
version = "0.1.0"
description = "streaming app"
authors = ["spacexjedi"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^1.1.2"
mutagen = "^1.45.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
